# version: '3.8'

services:
  nginx:
    build: 
      context: requirements/nginx/.
      args:
        TLS_KEY_DIR: ${TLS_KEY_DIR}
        TLS_KEY: ${TLS_KEY}
        TLS_CRT: ${TLS_CRT}
        TLS_SUBJ: ${TLS_SUBJ}
    image: nginx
    restart: always
    env_file:
      - .env
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - '443:443'
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
  wordpress:
    build: 
      context: requirements/wordpress/.
    image: wordpress
    restart: always
    env_file:
      - .env
    container_name: wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
  mariadb:
    build: requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    expose:
      - '3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress_data:
    name: wordpress_data
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  mariadb_data:
    name: mariadb_data
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb